### PR TITLE
Add hacks for BHNT 94

### PR DESCRIPTION
**Pull request by ligi**
cc @hartwork @vrde @herrherrmann @leopic @strathausen @ricott1

### CODE REVIEW

**Review by herrherrmann — APPROVED** [review]
Thanks!

**Comment by leopic** [comment]
Looks good to me, thank you!

**Review by leopic — APPROVED** [review]

**Review by hartwork — COMMENTED** [review]
Repository https://github.com/vrde/planner-planner seems private or misspelled. @vrde could you clarify?

**Comment by vrde** [comment]
I still have to decide about the license, but I've updated the repo, feel free to merge.

**Pull request merged**
